set -e

ASSIGNMENT_FOLDER=$(dirname $0)
DATASET_FOLDER=$ASSIGNMENT_FOLDER/../../dataset_2
CONFIG_FILE=$ASSIGNMENT_FOLDER/config.ini
EXECUTABLE_PATH=$ASSIGNMENT_FOLDER/build/cluster_extraction

$EXECUTABLE_PATH $DATASET_FOLDER $CONFIG_FILE -d